export const CATEGORIES = [
	{ id: 'joyous', name: 'Joyous', icon: '🎉' },
	{ id: 'smileys', name: 'Smileys', icon: '😊' },
	{ id: 'people', name: 'People', icon: '👋' },
	{ id: 'animals', name: 'Animals & Nature', icon: '🐶' },
	{ id: 'food', name: 'Food & Drink', icon: '🍔' },
	{ id: 'travel', name: 'Travel & Places', icon: '✈️' },
	{ id: 'activities', name: 'Activities', icon: '⚽' },
	{ id: 'objects', name: 'Objects', icon: '💡' },
	{ id: 'symbols', name: 'Symbols', icon: '💬' },
	{ id: 'flags', name: 'Flags', icon: '🇺🇳' },
];

export const SKIN_TONES = [
	{ id: 'default', modifier: '', name: 'Default', color: '#FFD700' },
	{ id: 'light', modifier: '\u{1F3FB}', name: 'Light', color: '#FFE0BD' },
	{ id: 'medium-light', modifier: '\u{1F3FC}', name: 'Medium-Light', color: '#F1C27D' },
	{ id: 'medium', modifier: '\u{1F3FD}', name: 'Medium', color: '#D29A6A' },
	{ id: 'medium-dark', modifier: '\u{1F3FE}', name: 'Medium-Dark', color: '#8D5524' },
	{ id: 'dark', modifier: '\u{1F3FF}', name: 'Dark', color: '#3D2B1F' },
];

export const DEFAULT_SKIN_TONE_INDEX = 3;

const EMOJIS = [
	['🎉', 'party popper', 'joyous', 'party celebration birthday congratulations confetti'],
	['🎊', 'confetti ball', 'joyous', 'confetti celebration party congratulations'],
	['🎈', 'balloon', 'joyous', 'balloon party celebration birthday'],
	['🎁', 'wrapped gift', 'joyous', 'gift present birthday christmas celebration'],
	['🎀', 'ribbon', 'joyous', 'ribbon decoration celebration'],
	['🥳', 'partying face', 'joyous', 'party celebration birthday congratulations festive'],
	['🥂', 'clinking glasses', 'joyous', 'cheers celebrate toast drink party celebration'],
	['🍾', 'bottle with popping cork', 'joyous', 'champagne celebration party bottle'],
	['🎇', 'sparkler', 'joyous', 'sparkler celebration fireworks night'],
	['🎆', 'fireworks', 'joyous', 'fireworks celebration new year independence'],
	['✨', 'sparkles', 'joyous', 'sparkles shine magic pretty celebration'],
	['🌟', 'glowing star', 'joyous', 'star glowing shining celebration magic'],
	['💫', 'dizzy star', 'joyous', 'dizzy star sparkle magic celebration'],
	['🎵', 'musical note', 'joyous', 'music note song melody celebration'],
	['🎶', 'musical notes', 'joyous', 'music notes song melody celebration'],
	['🎤', 'microphone', 'joyous', 'microphone sing karaoke performance celebration'],
	['🎸', 'guitar', 'joyous', 'guitar music instrument rock celebration'],
	['🎹', 'musical keyboard', 'joyous', 'piano keyboard music instrument celebration'],
	['🥁', 'drum', 'joyous', 'drum music instrument beat celebration'],
	['🎺', 'trumpet', 'joyous', 'trumpet music instrument jazz celebration'],
	['🎻', 'violin', 'joyous', 'violin music instrument classical celebration'],
	['🎬', 'clapper board', 'joyous', 'movie film clapper celebration premiere'],
	['🎭', 'performing arts', 'joyous', 'theater performing arts mask celebration'],
	['🎨', 'artist palette', 'joyous', 'art palette painting creativity celebration'],
	['🎪', 'circus tent', 'joyous', 'circus tent performance celebration'],
	['🎠', 'carousel horse', 'joyous', 'carousel horse carnival celebration'],
	['🎡', 'ferris wheel', 'joyous', 'ferris wheel amusement park celebration'],
	['🎢', 'roller coaster', 'joyous', 'roller coaster amusement park fun celebration'],
	['🎯', 'bullseye', 'joyous', 'target bullseye goal achievement celebration'],
	['🧩', 'puzzle piece', 'joyous', 'puzzle piece problem solving celebration'],
	['🏆', 'trophy', 'joyous', 'trophy award prize winner champion celebration'],
	['🥇', '1st place medal', 'joyous', 'gold medal first place winner celebration'],
	['🥈', '2nd place medal', 'joyous', 'silver medal second place winner celebration'],
	['🥉', '3rd place medal', 'joyous', 'bronze medal third place winner celebration'],
	['🎖️', 'military medal', 'joyous', 'medal military award honor celebration'],
	['🏅', 'sports medal', 'joyous', 'medal sports award winner celebration'],
	['🎗️', 'reminder ribbon', 'joyous', 'ribbon awareness remembrance celebration'],
	['🎫', 'ticket', 'joyous', 'ticket event concert movie celebration'],
	['🪅', 'pinata', 'joyous', 'pinata party celebration candy birthday'],
	['🪩', 'disco ball', 'joyous', 'disco ball dance party celebration nightclub'],
	['💃', 'woman dancing', 'joyous', 'dance woman dancing party celebration', true],
	['🕺', 'man dancing', 'joyous', 'dance man dancing party celebration', true],
	['👯', 'people with bunny ears', 'joyous', 'bunny ears dancing party celebration'],
	['🎊', 'confetti ball', 'joyous', 'confetti party celebration'],

	['😀', 'grinning face', 'smileys', 'grinning smile happy face'],
	['😃', 'grinning face with big eyes', 'smileys', 'grinning smile happy eyes face'],
	['😄', 'grinning face with smiling eyes', 'smileys', 'grinning smile happy eyes face'],
	['😁', 'beaming face with smiling eyes', 'smileys', 'beaming smile happy eyes face'],
	['😆', 'grinning squinting face', 'smileys', 'grinning squinting laugh happy face'],
	['😅', 'grinning face with sweat', 'smileys', 'grinning sweat nervous happy face'],
	['🤣', 'rolling on the floor laughing', 'smileys', 'rofl laughing funny hilarious face'],
	['😂', 'face with tears of joy', 'smileys', 'tears joy laughing cry happy face'],
	['🙂', 'slightly smiling face', 'smileys', 'smiling slight happy face'],
	['🙃', 'upside-down face', 'smileys', 'upside down silly funny face'],
	['🫠', 'melting face', 'smileys', 'melting hot melt face'],
	['😉', 'winking face', 'smileys', 'wink flirty funny face'],
	['😊', 'smiling face with smiling eyes', 'smileys', 'smiling blush happy eyes face'],
	['😇', 'smiling face with halo', 'smileys', 'halo angel innocent smile face'],
	['🥰', 'smiling face with hearts', 'smileys', 'hearts love adore crush face'],
	['😍', 'smiling face with heart-eyes', 'smileys', 'heart eyes love crush face'],
	['🤩', 'star-struck face', 'smileys', 'star struck excited amazed face'],
	['😘', 'face blowing a kiss', 'smileys', 'kiss blow love face'],
	['😗', 'kissing face', 'smileys', 'kiss face'],
	['😚', 'kissing face with closed eyes', 'smileys', 'kiss closed eyes face'],
	['😙', 'kissing face with smiling eyes', 'smileys', 'kiss smile eyes face'],
	['🥲', 'smiling face with tear', 'smileys', 'smile tear bittersweet emotional face'],
	['😋', 'face savoring food', 'smileys', 'yummy savor delicious tongue face'],
	['😛', 'face with tongue', 'smileys', 'tongue silly playful face'],
	['😜', 'winking face with tongue', 'smileys', 'wink tongue silly joke face'],
	['🤪', 'zany face', 'smileys', 'zany crazy wild silly face'],
	['😝', 'squinting face with tongue', 'smileys', 'squinting tongue silly taste face'],
	['🤑', 'money-mouth face', 'smileys', 'money mouth rich dollar face'],
	['🤗', 'smiling face with open hands', 'smileys', 'hug open hands welcome face'],
	['🤭', 'face with hand over mouth', 'smileys', 'hand mouth shocked secret oops face'],
	['🫢', 'face with open eyes and hand over mouth', 'smileys', 'open eyes hand mouth shocked face'],
	['🫣', 'face with peeking eye', 'smileys', 'peeking eye hiding peek face'],
	['🤫', 'shushing face', 'smileys', 'shush quiet silent secret face'],
	['🤔', 'thinking face', 'smileys', 'thinking consider ponder wonder face'],
	['🫡', 'saluting face', 'smileys', 'salute respect military face'],
	['🤐', 'zipper-mouth face', 'smileys', 'zipper mouth secret silent face'],
	['🤨', 'face with raised eyebrow', 'smileys', 'raised eyebrow skeptical suspicious face'],
	['😐', 'neutral face', 'smileys', 'neutral straight face'],
	['😑', 'expressionless face', 'smileys', 'expressionless deadpan unimpressed face'],
	['😶', 'face without mouth', 'smileys', 'no mouth silent speechless face'],
	['🫥', 'dotted line face', 'smileys', 'dotted line invisible hidden face'],
	['😶‍🌫️', 'face in clouds', 'smileys', 'clouds foggy distracted face'],
	['😏', 'smirking face', 'smileys', 'smirk smug confident suggestive face'],
	['😒', 'unamused face', 'smileys', 'unamused unimpressed annoyed face'],
	['🙄', 'face with rolling eyes', 'smileys', 'rolling eyes annoyed skeptical face'],
	['😬', 'grimacing face', 'smileys', 'grimace awkward nervous embarrassed face'],
	['😮‍💨', 'face exhaling', 'smileys', 'exhale sigh relief breath face'],
	['🤥', 'lying face', 'smileys', 'lying liar pinocchio nose face'],
	['🫨', 'shaking face', 'smileys', 'shaking earthquake shock face'],
	['😌', 'relieved face', 'smileys', 'relieved relieved calm peaceful face'],
	['😔', 'pensive face', 'smileys', 'pensive sad thoughtful melancholy face'],
	['😪', 'sleepy face', 'smileys', 'sleepy tired sleep face'],
	['🤤', 'drooling face', 'smileys', 'drool hungry sleep drooling face'],
	['😴', 'sleeping face', 'smileys', 'sleeping zzz tired asleep face'],
	['😷', 'face with medical mask', 'smileys', 'mask medical sick covid face'],
	['🤒', 'face with thermometer', 'smileys', 'thermometer sick ill fever face'],
	['🤕', 'face with head-bandage', 'smileys', 'bandage hurt injured face'],
	['🤢', 'nauseated face', 'smileys', 'nausea sick vomit disgust face'],
	['🤮', 'face vomiting', 'smileys', 'vomit sick throw up face'],
	['🤧', 'sneezing face', 'smileys', 'sneeze sick cold allergy face'],
	['🥵', 'hot face', 'smileys', 'hot overheated sweating fever face'],
	['🥶', 'cold face', 'smileys', 'cold freezing freezing icy face'],
	['🥴', 'woozy face', 'smileys', 'woozy drunk dizzy confused face'],
	['😵', 'face with crossed-out eyes', 'smileys', 'crossed eyes dizzy shocked face'],
	['😵‍💫', 'face with spiral eyes', 'smileys', 'spiral eyes dizzy hypnotized face'],
	['🤯', 'exploding head', 'smileys', 'exploding head mind blown shocked face'],
	['🤠', 'cowboy hat face', 'smileys', 'cowboy hat western wild west face'],
	['🥳', 'partying face', 'smileys', 'party celebration birthday festive face'],
	['🥸', 'disguised face', 'smileys', 'disguise mask costume hidden face'],
	['😎', 'smiling face with sunglasses', 'smileys', 'sunglasses cool chill awesome face'],
	['🤓', 'nerd face', 'smileys', 'nerd geek smart glasses face'],
	['🧐', 'face with monocle', 'smileys', 'monocle rich fancy sophisticated face'],
	['😕', 'confused face', 'smileys', 'confused puzzled unsure face'],
	['🫤', 'face with diagonal mouth', 'smileys', 'diagonal mouth confused unsure face'],
	['😟', 'worried face', 'smileys', 'worried anxious concerned face'],
	['🙁', 'slightly frowning face', 'smileys', 'frowning sad slight face'],
	['😮', 'face with open mouth', 'smileys', 'open mouth surprised shocked face'],
	['😯', 'hushed face', 'smileys', 'hushed surprised stunned face'],
	['😲', 'astonished face', 'smileys', 'astonished shocked amazed surprised face'],
	['😳', 'flushed face', 'smileys', 'flushed embarrassed shy blush face'],
	['🥺', 'pleading face', 'smileys', 'pleading begging puppy eyes face'],
	['🥹', 'face holding back tears', 'smileys', 'tears emotional cry touched face'],
	['😢', 'crying face', 'smileys', 'cry sad tear crying face'],
	['😭', 'loudly crying face', 'smileys', 'crying sob tears sad face'],
	['😤', 'face with steam from nose', 'smileys', 'steam nose frustrated angry face'],
	['😡', 'pouting face', 'smileys', 'pout angry mad furious face'],
	['😠', 'angry face', 'smileys', 'angry mad furious face'],
	['🤬', 'face with symbols on mouth', 'smileys', 'cursing swearing angry profanity face'],
	['💀', 'skull', 'smileys', 'skull death danger spooky'],
	['☠️', 'skull and crossbones', 'smileys', 'skull crossbones poison danger death'],

	['👋', 'waving hand', 'people', 'wave hello goodbye hand gesture', true],
	['🤚', 'raised back of hand', 'people', 'raised back hand stop gesture', true],
	['🖐️', 'hand with fingers splayed', 'people', 'hand fingers splayed stop gesture', true],
	['✋', 'raised hand', 'people', 'raised hand stop high five gesture', true],
	['🖖', 'vulcan salute', 'people', 'vulcan salute star trek spock gesture', true],
	['🫱', 'rightwards hand', 'people', 'rightwards hand gesture direction', true],
	['🫲', 'leftwards hand', 'people', 'leftwards hand gesture direction', true],
	['🫳', 'palm down hand', 'people', 'palm down hand gesture', true],
	['🫴', 'palm up hand', 'people', 'palm up hand gesture', true],
	['👌', 'OK hand', 'people', 'ok hand gesture perfect', true],
	['🤌', 'pinched fingers', 'people', 'pinched fingers italian gesture', true],
	['🤏', 'pinching hand', 'people', 'pinching hand small amount gesture', true],
	['✌️', 'victory hand', 'people', 'victory peace hand v gesture', true],
	['🤞', 'crossed fingers', 'people', 'crossed fingers luck hope gesture', true],
	['🫰', 'hand with index finger and thumb crossed', 'people', 'index thumb crossed gesture', true],
	['🤟', 'love-you gesture', 'people', 'love you gesture hand rock', true],
	['🤘', 'sign of the horns', 'people', 'horns rock metal gesture hand', true],
	['🤙', 'call me hand', 'people', 'call me hand gesture phone', true],
	['👈', 'backhand index pointing left', 'people', 'point left direction gesture', true],
	['👉', 'backhand index pointing right', 'people', 'point right direction gesture', true],
	['👆', 'backhand index pointing up', 'people', 'point up direction gesture', true],
	['🖕', 'middle finger', 'people', 'middle finger rude gesture', true],
	['👇', 'backhand index pointing down', 'people', 'point down direction gesture', true],
	['☝️', 'index pointing up', 'people', 'point up index gesture', true],
	['🫵', 'index pointing at the viewer', 'people', 'point at viewer you gesture', true],
	['👍', 'thumbs up', 'people', 'thumbs up like good approve gesture', true],
	['👎', 'thumbs down', 'people', 'thumbs down dislike bad gesture', true],
	['✊', 'raised fist', 'people', 'fist raised power solidarity gesture', true],
	['👊', 'oncoming fist', 'people', 'fist punch bump hit gesture', true],
	['🤛', 'left-facing fist', 'people', 'fist left bump gesture', true],
	['🤜', 'right-facing fist', 'people', 'fist right bump gesture', true],
	['👏', 'clapping hands', 'people', 'clap applause praise congratulations gesture', true],
	['🙌', 'raising hands', 'people', 'raise hands celebration praise gesture', true],
	['🫶', 'heart hands', 'people', 'heart hands love gesture', true],
	['👐', 'open hands', 'people', 'open hands open gesture', true],
	['🤲', 'palms up together', 'people', 'palms up together praying gesture', true],
	['🤝', 'handshake', 'people', 'handshake agreement deal partnership'],
	['🙏', 'folded hands', 'people', 'pray please thank you gesture', true],
	['✍️', 'writing hand', 'people', 'writing hand write gesture', true],
	['💅', 'nail polish', 'people', 'nail polish carefree fancy gesture', true],
	['🤳', 'selfie', 'people', 'selfie camera phone gesture', true],
	['💪', 'flexed biceps', 'people', 'bicep flex strong muscle arm gesture', true],
	['🦵', 'leg', 'people', 'leg limb body part', true],
	['🦶', 'foot', 'people', 'foot body part', true],
	['👂', 'ear', 'people', 'ear hearing listen body', true],
	['👃', 'nose', 'people', 'nose smell body part', true],
	['🧠', 'brain', 'people', 'brain mind intelligence smart'],
	['🫀', 'anatomical heart', 'people', 'heart anatomy organ body'],
	['🫁', 'lungs', 'people', 'lungs breathe respiratory organ'],
	['👀', 'eyes', 'people', 'eyes look see watch body'],
	['👁️', 'eye', 'people', 'eye look see body part'],
	['👅', 'tongue', 'people', 'tongue taste lick body'],
	['👄', 'mouth', 'people', 'mouth lips kiss body'],
	['🦷', 'tooth', 'people', 'tooth teeth dental body'],
	['🦴', 'bone', 'people', 'bone skeleton body'],
	['🧑', 'person', 'people', 'person adult generic', true],
	['👨', 'man', 'people', 'man adult male', true],
	['👩', 'woman', 'people', 'woman adult female', true],
	['🧔', 'person beard', 'people', 'beard person man facial hair', true],
	['👴', 'old man', 'people', 'old man elderly grandpa', true],
	['👵', 'old woman', 'people', 'old woman elderly grandma', true],
	['👶', 'baby', 'people', 'baby infant child', true],
	['🧒', 'child', 'people', 'child kid', true],
	['👦', 'boy', 'people', 'boy child male kid', true],
	['👧', 'girl', 'people', 'girl child female kid', true],

	['🐶', 'dog face', 'animals', 'dog pet animal face'],
	['🐱', 'cat face', 'animals', 'cat pet animal face'],
	['🐭', 'mouse face', 'animals', 'mouse rodent animal face'],
	['🐹', 'hamster', 'animals', 'hamster pet rodent animal'],
	['🐰', 'rabbit face', 'animals', 'rabbit bunny pet animal face'],
	['🦊', 'fox', 'animals', 'fox animal clever sly'],
	['🐻', 'bear', 'animals', 'bear animal forest'],
	['🐼', 'panda', 'animals', 'panda bear animal china'],
	['🐻‍❄️', 'polar bear', 'animals', 'polar bear arctic animal'],
	['🐨', 'koala', 'animals', 'koala bear australia animal'],
	['🐯', 'tiger face', 'animals', 'tiger cat animal face'],
	['🦁', 'lion', 'animals', 'lion animal king wild'],
	['🐮', 'cow face', 'animals', 'cow animal face farm'],
	['🐷', 'pig face', 'animals', 'pig animal face farm'],
	['🐸', 'frog', 'animals', 'frog animal amphibian'],
	['🐵', 'monkey face', 'animals', 'monkey primate animal face'],
	['🐒', 'monkey', 'animals', 'monkey primate animal'],
	['🐔', 'chicken', 'animals', 'chicken bird farm animal'],
	['🐧', 'penguin', 'animals', 'penguin bird antarctic animal'],
	['🐦', 'bird', 'animals', 'bird animal fly'],
	['🐤', 'baby chick', 'animals', 'chick baby bird chicken'],
	['🦅', 'eagle', 'animals', 'eagle bird predator america'],
	['🦉', 'owl', 'animals', 'owl bird wise night'],
	['🦇', 'bat', 'animals', 'bat animal vampire night'],
	['🐺', 'wolf', 'animals', 'wolf animal howl wild'],
	['🐗', 'boar', 'animals', 'boar pig wild animal'],
	['🐴', 'horse face', 'animals', 'horse animal face'],
	['🦄', 'unicorn', 'animals', 'unicorn mythical fantasy magical'],
	['🐝', 'honeybee', 'animals', 'bee honey insect buzz'],
	['🐛', 'bug', 'animals', 'bug insect caterpillar'],
	['🦋', 'butterfly', 'animals', 'butterfly insect beautiful wings'],
	['🐌', 'snail', 'animals', 'snail slow shell animal'],
	['🐞', 'lady beetle', 'animals', 'ladybug beetle insect lucky'],
	['🐜', 'ant', 'animals', 'ant insect bug animal'],
	['🦗', 'cricket', 'animals', 'cricket insect grasshopper'],
	['🕷️', 'spider', 'animals', 'spider insect web arachnid'],
	['🦂', 'scorpion', 'animals', 'scorpion animal venom desert'],
	['🦟', 'mosquito', 'animals', 'mosquito insect malaria bite'],
	['🪰', 'fly', 'animals', 'fly insect pest'],
	['🪱', 'worm', 'animals', 'worm animal earthworm'],
	['🐢', 'turtle', 'animals', 'turtle slow reptile animal'],
	['🐍', 'snake', 'animals', 'snake reptile dangerous animal'],
	['🦎', 'lizard', 'animals', 'lizard reptile gecko animal'],
	['🦖', 'T-Rex', 'animals', 'trex dinosaur fossil animal'],
	['🦕', 'sauropod', 'animals', 'sauropod dinosaur long neck animal'],
	['🐙', 'octopus', 'animals', 'octopus sea ocean animal tentacles'],
	['🦑', 'squid', 'animals', 'squid sea ocean animal'],
	['🦐', 'shrimp', 'animals', 'shrimp seafood ocean animal'],
	['🐳', 'spouting whale', 'animals', 'whale sea ocean animal water'],
	['🐬', 'dolphin', 'animals', 'dolphin sea ocean animal friendly'],
	['🦭', 'seal', 'animals', 'seal sea lion animal'],
	['🐊', 'crocodile', 'animals', 'crocodile reptile dangerous animal'],
	['🐅', 'tiger', 'animals', 'tiger big cat wild animal'],
	['🐆', 'leopard', 'animals', 'leopard big cat spots animal'],
	['🦓', 'zebra', 'animals', 'zebra stripes animal africa'],
	['🦍', 'gorilla', 'animals', 'gorilla ape primate animal'],
	['🦧', 'orangutan', 'animals', 'orangutan ape primate animal'],
	['🐘', 'elephant', 'animals', 'elephant big animal africa'],
	['🦣', 'mammoth', 'animals', 'mammoth extinct elephant ice age'],
	['🦛', 'hippopotamus', 'animals', 'hippo animal africa river'],
	['🦏', 'rhinoceros', 'animals', 'rhino animal africa horn'],
	['🐪', 'camel', 'animals', 'camel desert animal hump'],
	['🐫', 'two-hump camel', 'animals', 'camel bactrian desert animal'],
	['🦒', 'giraffe', 'animals', 'giraffe tall animal africa'],
	['🦘', 'kangaroo', 'animals', 'kangaroo australia hop animal'],
	['🦬', 'bison', 'animals', 'bison buffalo animal american'],
	['🐃', 'water buffalo', 'animals', 'buffalo water animal asia'],
	['🐄', 'cow', 'animals', 'cow farm animal milk'],
	['🦙', 'llama', 'animals', 'llama alpaca animal south america'],
	['🦥', 'sloth', 'animals', 'sloth slow animal tree'],
	['🦦', 'otter', 'animals', 'otter playful animal water'],
	['🦨', 'skunk', 'animals', 'skunk smell animal stripe'],
	['🦫', 'beaver', 'animals', 'beaver dam animal rodent'],

	['🍔', 'hamburger', 'food', 'burger fast food meat'],
	['🍟', 'french fries', 'food', 'fries potato fast food'],
	['🍕', 'pizza', 'food', 'pizza italian cheese food'],
	['🌭', 'hot dog', 'food', 'hotdog sausage fast food'],
	['🥪', 'sandwich', 'food', 'sandwich bread lunch food'],
	['🌮', 'taco', 'food', 'taco mexican food'],
	['🌯', 'burrito', 'food', 'burrito mexican wrap food'],
	['🥙', 'stuffed flatbread', 'food', 'flatbread gyro kebab food'],
	['🧆', 'falafel', 'food', 'falafel middle eastern chickpea food'],
	['🥚', 'egg', 'food', 'egg breakfast food'],
	['🍳', 'cooking', 'food', 'frying pan egg breakfast cooking'],
	['🥘', 'shallow pan of food', 'food', 'paella pan food cooking'],
	['🍲', 'pot of food', 'food', 'stew pot soup food'],
	['🥣', 'bowl with spoon', 'food', 'cereal breakfast bowl soup'],
	['🥗', 'green salad', 'food', 'salad healthy vegetable food'],
	['🍿', 'popcorn', 'food', 'popcorn movie snack food'],
	['🧈', 'butter', 'food', 'butter dairy spread food'],
	['🧂', 'salt', 'food', 'salt seasoning shaker food'],
	['🥫', 'canned food', 'food', 'can canned food preserve'],
	['🍱', 'bento box', 'food', 'bento japanese lunch box food'],
	['🍘', 'rice cracker', 'food', 'rice cracker japanese snack food'],
	['🍙', 'rice ball', 'food', 'rice ball onigiri japanese food'],
	['🍚', 'cooked rice', 'food', 'rice cooked grain food'],
	['🍛', 'curry rice', 'food', 'curry rice indian food'],
	['🍜', 'steaming bowl', 'food', 'noodles ramen soup food'],
	['🍝', 'spaghetti', 'food', 'spaghetti pasta italian food'],
	['🍠', 'roasted sweet potato', 'food', 'sweet potato roasted food'],
	['🍢', 'oden', 'food', 'oden japanese skewer food'],
	['🍣', 'sushi', 'food', 'sushi japanese fish food'],
	['🍤', 'fried shrimp', 'food', 'shrimp tempura fried food'],
	['🍥', 'fish cake with swirl', 'food', 'fish cake naruto japanese food'],
	['🥮', 'moon cake', 'food', 'moon cake mid-autumn festival food'],
	['🍡', 'dango', 'food', 'dango japanese dessert sweet food'],
	['🥟', 'dumpling', 'food', 'dumpling asian food'],
	['🥠', 'fortune cookie', 'food', 'fortune cookie chinese food'],
	['🥡', 'takeout box', 'food', 'takeout box chinese food container'],
	['🍦', 'soft ice cream', 'food', 'ice cream soft serve dessert'],
	['🍧', 'shaved ice', 'food', 'shaved ice dessert sweet'],
	['🍨', 'ice cream', 'food', 'ice cream dessert sweet bowl'],
	['🍩', 'doughnut', 'food', 'doughnut donut dessert sweet'],
	['🍪', 'cookie', 'food', 'cookie dessert sweet snack'],
	['🎂', 'birthday cake', 'food', 'birthday cake celebration dessert'],
	['🍰', 'shortcake', 'food', 'cake strawberry dessert sweet'],
	['🧁', 'cupcake', 'food', 'cupcake dessert sweet bakery'],
	['🥧', 'pie', 'food', 'pie dessert sweet pastry'],
	['🍫', 'chocolate bar', 'food', 'chocolate candy bar sweet'],
	['🍬', 'candy', 'food', 'candy sweet lollipop'],
	['🍭', 'lollipop', 'food', 'lollipop candy sweet sucker'],
	['🍮', 'custard', 'food', 'custard pudding dessert sweet'],
	['🍯', 'honey pot', 'food', 'honey sweet pot food'],
	['🍼', 'baby bottle', 'food', 'baby bottle milk drink'],
	['🥛', 'glass of milk', 'food', 'milk glass drink'],
	['☕', 'hot beverage', 'food', 'coffee tea hot drink'],
	['🫖', 'teapot', 'food', 'teapot tea drink'],
	['🍵', 'teacup without handle', 'food', 'tea green tea cup drink'],
	['🍶', 'sake', 'food', 'sake rice wine japanese drink'],
	['🍾', 'bottle with popping cork', 'food', 'champagne bottle wine drink'],
	['🍷', 'wine glass', 'food', 'wine glass drink'],
	['🍸', 'cocktail glass', 'food', 'cocktail martini drink'],
	['🍹', 'tropical drink', 'food', 'tropical drink juice cocktail'],
	['🍺', 'beer mug', 'food', 'beer mug drink alcohol'],
	['🍻', 'clinking beer mugs', 'food', 'beer cheers toast drink'],
	['🥂', 'clinking glasses', 'food', 'champagne cheers toast drink'],
	['🥃', 'tumbler glass', 'food', 'whiskey glass drink liquor'],
	['🫗', 'pouring liquid', 'food', 'pour liquid drink water'],
	['🥤', 'cup with straw', 'food', 'cup straw soda drink'],
	['🧋', 'bubble tea', 'food', 'bubble tea boba milk tea drink'],
	['🫙', 'jar', 'food', 'jar container food storage'],
	['🍇', 'grapes', 'food', 'grapes fruit wine'],
	['🍈', 'melon', 'food', 'melon fruit'],
	['🍉', 'watermelon', 'food', 'watermelon fruit summer'],
	['🍊', 'tangerine', 'food', 'tangerine orange citrus fruit'],
	['🍋', 'lemon', 'food', 'lemon citrus fruit sour'],
	['🍌', 'banana', 'food', 'banana fruit tropical'],
	['🍍', 'pineapple', 'food', 'pineapple fruit tropical'],
	['🥭', 'mango', 'food', 'mango fruit tropical'],
	['🍎', 'red apple', 'food', 'apple fruit red'],
	['🍏', 'green apple', 'food', 'apple fruit green'],
	['🍐', 'pear', 'food', 'pear fruit'],
	['🍑', 'peach', 'food', 'peach fruit'],
	['🍒', 'cherries', 'food', 'cherries fruit red'],
	['🍓', 'strawberry', 'food', 'strawberry fruit berry'],
	['🫐', 'blueberries', 'food', 'blueberry berries fruit'],
	['🥝', 'kiwi fruit', 'food', 'kiwi fruit'],
	['🍅', 'tomato', 'food', 'tomato vegetable fruit'],
	['🫒', 'olive', 'food', 'olive fruit oil'],
	['🥥', 'coconut', 'food', 'coconut fruit tropical'],
	['🥑', 'avocado', 'food', 'avocado fruit toast'],
	['🍆', 'eggplant', 'food', 'eggplant aubergine vegetable'],
	['🥔', 'potato', 'food', 'potato vegetable tuber'],
	['🥕', 'carrot', 'food', 'carrot vegetable orange'],
	['🌽', 'corn', 'food', 'corn maize vegetable'],
	['🌶️', 'hot pepper', 'food', 'pepper hot spicy chili'],
	['🫑', 'bell pepper', 'food', 'bell pepper capsicum vegetable'],
	['🥒', 'cucumber', 'food', 'cucumber vegetable salad'],
	['🥬', 'leafy green', 'food', 'lettuce cabbage green vegetable'],
	['🥦', 'broccoli', 'food', 'broccoli vegetable green'],
	['🧄', 'garlic', 'food', 'garlic seasoning vegetable'],
	['🧅', 'onion', 'food', 'onion vegetable cooking'],
	['🥜', 'peanuts', 'food', 'peanuts nuts snack'],
	['🫘', 'beans', 'food', 'beans legumes food'],
	['🌰', 'chestnut', 'food', 'chestnut nut fall'],
	['🫚', 'ginger root', 'food', 'ginger root spice'],
	['🫛', 'pea pod', 'food', 'pea pod vegetable'],

	['🚗', 'car', 'travel', 'car automobile vehicle transportation'],
	['🚕', 'taxi', 'travel', 'taxi cab vehicle transportation'],
	['🚙', 'SUV', 'travel', 'suv vehicle car transportation'],
	['🚌', 'bus', 'travel', 'bus vehicle transportation public'],
	['🚎', 'trolleybus', 'travel', 'trolley bus transportation'],
	['🏎️', 'racing car', 'travel', 'race car formula one speed'],
	['🚓', 'police car', 'travel', 'police car law enforcement'],
	['🚑', 'ambulance', 'travel', 'ambulance medical emergency vehicle'],
	['🚒', 'fire engine', 'travel', 'fire truck engine emergency'],
	['🚐', 'minibus', 'travel', 'minibus van vehicle'],
	['🚚', 'delivery truck', 'travel', 'truck delivery vehicle transport'],
	['🚛', 'articulated lorry', 'travel', 'lorry truck transport vehicle'],
	['🚜', 'tractor', 'travel', 'tractor farm vehicle'],
	['🏍️', 'motorcycle', 'travel', 'motorcycle bike motorbike'],
	['🛵', 'scooter', 'travel', 'scooter bike motor'],
	['🛴', 'kick scooter', 'travel', 'kick scooter push'],
	['🚲', 'bicycle', 'travel', 'bicycle bike cycle'],
	['🛹', 'skateboard', 'travel', 'skateboard board'],
	['🛼', 'roller skate', 'travel', 'roller skate inline'],
	['🚏', 'bus stop', 'travel', 'bus stop sign transportation'],
	['🛣️', 'motorway', 'travel', 'motorway highway road'],
	['🛤️', 'railway track', 'travel', 'railway track train'],
	['⛽', 'fuel pump', 'travel', 'fuel gas pump station'],
	['🛩️', 'small airplane', 'travel', 'airplane small plane fly'],
	['✈️', 'airplane', 'travel', 'airplane plane fly travel'],
	['🛫', 'airplane departure', 'travel', 'airplane takeoff departure fly'],
	['🛬', 'airplane arrival', 'travel', 'airplane landing arrival fly'],
	['🚁', 'helicopter', 'travel', 'helicopter rotorcraft fly'],
	['🚟', 'suspension railway', 'travel', 'suspension railway train'],
	['🚠', 'mountain cableway', 'travel', 'cable car mountain gondola'],
	['🚡', 'aerial tramway', 'travel', 'tramway cable car aerial'],
	['🛰️', 'satellite', 'travel', 'satellite space orbit communication'],
	['🚀', 'rocket', 'travel', 'rocket space launch ship'],
	['🛸', 'flying saucer', 'travel', 'ufo alien flying saucer'],
	['🚢', 'ship', 'travel', 'ship boat vessel transportation'],
	['⛵', 'sailboat', 'travel', 'sailboat yacht boat sail'],
	['🛶', 'canoe', 'travel', 'canoe kayak boat paddle'],
	['🚤', 'speedboat', 'travel', 'speedboat boat motor fast'],
	['🛳️', 'passenger ship', 'travel', 'passenger ship cruise ferry'],
	['⚓', 'anchor', 'travel', 'anchor ship boat nautical'],
	['🗺️', 'world map', 'travel', 'map world geography travel'],
	['🌍', 'globe showing Europe-Africa', 'travel', 'globe earth world africa europe'],
	['🌎', 'globe showing Americas', 'travel', 'globe earth world americas'],
	['🌏', 'globe showing Asia-Australia', 'travel', 'globe earth world asia australia'],
	['🧭', 'compass', 'travel', 'compass navigation direction travel'],
	['🏔️', 'snow-capped mountain', 'travel', 'mountain snow peak'],
	['⛰️', 'mountain', 'travel', 'mountain peak'],
	['🌋', 'volcano', 'travel', 'volcano eruption mountain lava'],
	['🏖️', 'beach with umbrella', 'travel', 'beach umbrella sand vacation'],
	['🏝️', 'desert island', 'travel', 'island desert tropical beach'],
	['🏜️', 'desert', 'travel', 'desert sand arid'],
	['🏗️', 'building construction', 'travel', 'construction building crane'],
	['🏘️', 'houses', 'travel', 'houses buildings neighborhood'],
	['🏙️', 'cityscape', 'travel', 'city skyline buildings urban'],
	['🌃', 'night with stars', 'travel', 'night stars city evening'],
	['🌆', 'cityscape at dusk', 'travel', 'city dusk evening sunset'],
	['🌇', 'sunset', 'travel', 'sunset evening dusk city'],
	['🌉', 'bridge at night', 'travel', 'bridge night water'],
	['🎠', 'carousel horse', 'travel', 'carousel horse amusement park'],
	['🎡', 'ferris wheel', 'travel', 'ferris wheel amusement park fair'],
	['🎢', 'roller coaster', 'travel', 'roller coaster amusement park fun'],

	['⚽', 'soccer ball', 'activities', 'soccer football ball sport'],
	['🏀', 'basketball', 'activities', 'basketball ball sport'],
	['🏈', 'american football', 'activities', 'football american sport ball'],
	['⚾', 'baseball', 'activities', 'baseball ball sport'],
	['🥎', 'softball', 'activities', 'softball ball sport'],
	['🎾', 'tennis', 'activities', 'tennis racquet ball sport'],
	['🏐', 'volleyball', 'activities', 'volleyball ball sport'],
	['🏉', 'rugby football', 'activities', 'rugby football sport ball'],
	['🥏', 'flying disc', 'activities', 'frisbee disc ultimate sport'],
	['🎳', 'bowling', 'activities', 'bowling ball pin sport'],
	['🏏', 'cricket', 'activities', 'cricket bat ball sport'],
	['🏑', 'field hockey', 'activities', 'hockey field stick sport'],
	['🏒', 'ice hockey', 'activities', 'hockey ice stick puck sport'],
	['🥍', 'lacrosse', 'activities', 'lacrosse stick ball sport'],
	['🏓', 'ping pong', 'activities', 'table tennis ping pong paddle sport'],
	['🏸', 'badminton', 'activities', 'badminton shuttlecock racquet sport'],
	['🥊', 'boxing glove', 'activities', 'boxing glove fight sport'],
	['🥋', 'martial arts uniform', 'activities', 'martial arts karate judo uniform'],
	['🥅', 'goal net', 'activities', 'goal net soccer hockey sport'],
	['⛳', 'flag in hole', 'activities', 'golf flag hole sport'],
	['⛸️', 'ice skate', 'activities', 'ice skate skating sport'],
	['🎣', 'fishing pole', 'activities', 'fishing pole fish sport'],
	['🤿', 'diving mask', 'activities', 'diving mask scuba snorkel'],
	['🎽', 'running shirt', 'activities', 'running shirt sash sport'],
	['🎿', 'skis', 'activities', 'ski snow ski sport'],
	['🛷', 'sled', 'activities', 'sled snow winter sport'],
	['🥌', 'curling stone', 'activities', 'curling stone sport'],
	['🎯', 'bullseye', 'activities', 'dart target bullseye game'],
	['🪀', 'yo-yo', 'activities', 'yoyo toy game play'],
	['🪁', 'kite', 'activities', 'kite fly sky toy'],
	['🎱', 'pool 8 ball', 'activities', 'billiards pool 8 ball game'],
	['🔮', 'crystal ball', 'activities', 'crystal ball fortune psychic'],
	['🕹️', 'joystick', 'activities', 'joystick video game controller'],
	['🎮', 'video game', 'activities', 'video game controller play'],
	['🃏', 'joker', 'activities', 'joker card playing game'],
	['🎴', 'flower playing cards', 'activities', 'flower cards playing japanese'],
	['🀄', 'mahjong red dragon', 'activities', 'mahjong tile game'],
	['🎲', 'game die', 'activities', 'dice game board random'],
	['🧩', 'puzzle piece', 'activities', 'puzzle piece game connect'],
	['🧸', 'teddy bear', 'activities', 'teddy bear toy stuffed play'],
	['🪅', 'pinata', 'activities', 'pinata party candy game'],
	['🪩', 'disco ball', 'activities', 'disco ball dance party music'],
	['♟️', 'chess pawn', 'activities', 'chess pawn game strategy'],
	['🎭', 'performing arts', 'activities', 'theater mask drama performance'],
	['🎨', 'artist palette', 'activities', 'art palette painting creativity'],
	['🎬', 'clapper board', 'activities', 'clapper movie film director'],
	['🎤', 'microphone', 'activities', 'microphone sing karaoke perform'],
	['🎧', 'headphone', 'activities', 'headphone music listen audio'],
	['🎼', 'musical score', 'activities', 'music score sheet notes'],
	['🎹', 'musical keyboard', 'activities', 'piano keyboard music instrument'],
	['🥁', 'drum', 'activities', 'drum music instrument beat'],
	['🪘', 'long drum', 'activities', 'drum long music instrument'],
	['🎺', 'trumpet', 'activities', 'trumpet music instrument brass'],
	['🎸', 'guitar', 'activities', 'guitar music instrument string'],
	['🪕', 'banjo', 'activities', 'banjo music instrument string'],
	['🎻', 'violin', 'activities', 'violin music instrument string'],
	['🎵', 'musical note', 'activities', 'music note song melody'],
	['🎶', 'musical notes', 'activities', 'music notes song melody'],

	['💡', 'light bulb', 'objects', 'light bulb idea electricity'],
	['🔦', 'flashlight', 'objects', 'flashlight torch light'],
	['🏮', 'red paper lantern', 'objects', 'lantern red asian light'],
	['🪔', 'diya lamp', 'objects', 'diya lamp oil light deepavali'],
	['📘', 'blue book', 'objects', 'book blue reading'],
	['📗', 'green book', 'objects', 'book green reading'],
	['📕', 'red book', 'objects', 'book red reading'],
	['📙', 'orange book', 'objects', 'book orange reading'],
	['📓', 'notebook', 'objects', 'notebook writing journal'],
	['📔', 'notebook with decorative cover', 'objects', 'notebook decorated cover'],
	['📒', 'ledger', 'objects', 'ledger notebook accounting'],
	['📚', 'books', 'objects', 'books library reading stack'],
	['📖', 'open book', 'objects', 'book open reading'],
	['🔖', 'bookmark', 'objects', 'bookmark mark page'],
	['📎', 'paperclip', 'objects', 'paperclip attach document'],
	['🖇️', 'linked paperclips', 'objects', 'paperclips linked attached'],
	['📐', 'triangular ruler', 'objects', 'ruler triangle geometry'],
	['📏', 'straight ruler', 'objects', 'ruler straight measure'],
	['📌', 'pushpin', 'objects', 'pushpin pin map'],
	['📍', 'round pushpin', 'objects', 'pushpin round pin map'],
	['✂️', 'scissors', 'objects', 'scissors cut tool'],
	['🖊️', 'pen', 'objects', 'pen writing tool'],
	['🖋️', 'fountain pen', 'objects', 'fountain pen writing'],
	['✒️', 'black nib', 'objects', 'nib pen writing'],
	['🖌️', 'paintbrush', 'objects', 'paintbrush painting art'],
	['🖍️', 'crayon', 'objects', 'crayon drawing art color'],
	['📝', 'memo', 'objects', 'memo note writing document'],
	['📁', 'file folder', 'objects', 'folder file directory'],
	['📂', 'open file folder', 'objects', 'folder open file'],
	['🗂️', 'card index dividers', 'objects', 'dividers card index folder'],
	['📅', 'calendar', 'objects', 'calendar date schedule'],
	['📆', 'tear-off calendar', 'objects', 'calendar tear off date'],
	['🗒️', 'spiral notepad', 'objects', 'notepad spiral notes'],
	['🗓️', 'spiral calendar', 'objects', 'calendar spiral date'],
	['📇', 'card index', 'objects', 'card index rolodex contacts'],
	['📋', 'clipboard', 'objects', 'clipboard notes list'],
	['📉', 'chart decreasing', 'objects', 'chart down decrease graph'],
	['📈', 'chart increasing', 'objects', 'chart up increase growth graph'],
	['📊', 'bar chart', 'objects', 'chart bar graph data'],
	['📃', 'page with curl', 'objects', 'page curl document'],
	['📄', 'page facing up', 'objects', 'page document file'],
	['📑', 'bookmark tabs', 'objects', 'bookmark tabs marks'],
	['🔒', 'locked', 'objects', 'lock closed secure privacy'],
	['🔓', 'unlocked', 'objects', 'lock open unlock security'],
	['🔐', 'locked with key', 'objects', 'lock key secure closed'],
	['🔑', 'key', 'objects', 'key lock unlock password'],
	['🗝️', 'old key', 'objects', 'key old antique'],
	['🔨', 'hammer', 'objects', 'hammer tool build'],
	['🪓', 'axe', 'objects', 'axe wood chop tool'],
	['⛏️', 'pick', 'objects', 'pick mining tool'],
	['⚒️', 'hammer and pick', 'objects', 'hammer pick tool mining'],
	['🛠️', 'hammer and wrench', 'objects', 'hammer wrench tool repair'],
	['🔧', 'wrench', 'objects', 'wrench tool repair'],
	['🔩', 'nut and bolt', 'objects', 'nut bolt hardware tool'],
	['⚙️', 'gear', 'objects', 'gear cog settings mechanical'],
	['🖥️', 'desktop computer', 'objects', 'desktop computer pc monitor'],
	['💻', 'laptop', 'objects', 'laptop computer notebook'],
	['⌨️', 'keyboard', 'objects', 'keyboard computer type'],
	['🖨️', 'printer', 'objects', 'printer print document'],
	['💽', 'computer disk', 'objects', 'disk computer minidisc'],
	['💾', 'floppy disk', 'objects', 'floppy disk save computer'],
	['💿', 'optical disk', 'objects', 'cd dvd disk computer'],
	['📀', 'dvd', 'objects', 'dvd disk video movie'],
	['📷', 'camera', 'objects', 'camera photo photography'],
	['📸', 'camera with flash', 'objects', 'camera flash photo'],
	['📹', 'video camera', 'objects', 'video camera camcorder'],
	['🎥', 'movie camera', 'objects', 'movie camera film video'],
	['📽️', 'film projector', 'objects', 'film projector movie cinema'],
	['🎞️', 'film frames', 'objects', 'film frames strip movie'],
	['📞', 'telephone receiver', 'objects', 'telephone phone handset'],
	['☎️', 'telephone', 'objects', 'telephone phone landline'],
	['📟', 'pager', 'objects', 'pager beeper retro'],
	['📠', 'fax machine', 'objects', 'fax machine document'],
	['🔋', 'battery', 'objects', 'battery power energy charge'],
	['🪫', 'low battery', 'objects', 'battery low dead charge'],
	['🔌', 'electric plug', 'objects', 'plug power electricity'],
	['💡', 'light bulb', 'objects', 'bulb light idea electricity'],
	['🔦', 'flashlight', 'objects', 'flashlight torch light'],
	['🕯️', 'candle', 'objects', 'candle light fire wax'],
	['🪣', 'bucket', 'objects', 'bucket pail container water'],
	['🧹', 'broom', 'objects', 'broom sweep clean'],
	['🪠', 'plunger', 'objects', 'plunger toilet unclog'],
	['🧺', 'basket', 'objects', 'basket laundry picnic'],
	['🧻', 'roll of paper', 'objects', 'toilet paper roll tissue'],
	['🪣', 'bucket', 'objects', 'bucket pail'],
	['🧼', 'soap', 'objects', 'soap clean wash hygiene'],
	['🫧', 'bubbles', 'objects', 'bubbles soap clean bath'],
	['🪥', 'toothbrush', 'objects', 'toothbrush teeth dental hygiene'],
	['🧽', 'sponge', 'objects', 'sponge clean wash scrub'],
	['🧴', 'lotion bottle', 'objects', 'lotion bottle moisturizer shampoo'],
	['🪞', 'mirror', 'objects', 'mirror reflection face'],
	['🪒', 'razor', 'objects', 'razor shave grooming'],
	['🪮', 'comb', 'objects', 'comb hair brush grooming'],
	['💈', 'barber pole', 'objects', 'barber pole haircut salon'],

	['💬', 'speech balloon', 'symbols', 'speech balloon chat talk message'],
	['🗯️', 'right anger bubble', 'symbols', 'anger bubble angry shout'],
	['💭', 'thought balloon', 'symbols', 'thought balloon think idea'],
	['💤', 'zzz', 'symbols', 'zzz sleeping tired asleep'],
	['💢', 'anger symbol', 'symbols', 'anger symbol mad frustrated'],
	['💣', 'bomb', 'symbols', 'bomb explode danger'],
	['💥', 'collision', 'symbols', 'collision boom explode impact'],
	['💦', 'sweat droplets', 'symbols', 'sweat drops water exercise'],
	['💨', 'dashing away', 'symbols', 'dash running fast smoke wind'],
	['💫', 'dizzy', 'symbols', 'dizzy star sparkle magic'],
	['💪', 'flexed biceps', 'symbols', 'bicep strong muscle power'],
	['🫦', 'biting lip', 'symbols', 'bite lip nervous flirty'],
	['💀', 'skull', 'symbols', 'skull death danger spooky'],
	['☠️', 'skull and crossbones', 'symbols', 'skull crossbones poison danger'],
	['👽', 'alien', 'symbols', 'alien extraterrestrial ufo monster'],
	['👾', 'alien monster', 'symbols', 'alien monster space invader game'],
	['🤖', 'robot', 'symbols', 'robot machine ai android'],
	['💩', 'pile of poo', 'symbols', 'poop poop toilet humor'],
	['😺', 'grinning cat', 'symbols', 'cat smile happy face'],
	['😸', 'grinning cat with smiling eyes', 'symbols', 'cat smile happy eyes'],
	['😹', 'cat with tears of joy', 'symbols', 'cat tears joy laugh'],
	['😻', 'smiling cat with heart-eyes', 'symbols', 'cat heart eyes love'],
	['😼', 'cat with wry smile', 'symbols', 'cat wry smile smirk'],
	['😽', 'kissing cat', 'symbols', 'cat kiss face'],
	['🙀', 'weary cat', 'symbols', 'cat weary tired surprised'],
	['😿', 'crying cat', 'symbols', 'cat cry tear sad'],
	['😾', 'pouting cat', 'symbols', 'cat pout angry'],
	['❤️', 'red heart', 'symbols', 'heart red love passion'],
	['🧡', 'orange heart', 'symbols', 'heart orange love'],
	['💛', 'yellow heart', 'symbols', 'heart yellow love friendship'],
	['💚', 'green heart', 'symbols', 'heart green love envy'],
	['💙', 'blue heart', 'symbols', 'heart blue love'],
	['💜', 'purple heart', 'symbols', 'heart purple love'],
	['🖤', 'black heart', 'symbols', 'heart black love dark'],
	['🤍', 'white heart', 'symbols', 'heart white love pure'],
	['🤎', 'brown heart', 'symbols', 'heart brown love'],
	['💔', 'broken heart', 'symbols', 'heart broken sad breakup'],
	['❤️‍🔥', 'heart on fire', 'symbols', 'heart fire love passion burning'],
	['❤️‍🩹', 'mending heart', 'symbols', 'heart mending healing recovery'],
	['💕', 'two hearts', 'symbols', 'hearts two love couple'],
	['💞', 'revolving hearts', 'symbols', 'hearts revolving love'],
	['💓', 'beating heart', 'symbols', 'heart beating pulse love'],
	['💗', 'growing heart', 'symbols', 'heart growing love pink'],
	['💖', 'sparkling heart', 'symbols', 'heart sparkling love pretty'],
	['💘', 'heart with arrow', 'symbols', 'heart arrow love cupid'],
	['💝', 'heart with ribbon', 'symbols', 'heart ribbon gift love'],
	['💟', 'heart decoration', 'symbols', 'heart decoration symbol'],
	['☮️', 'peace symbol', 'symbols', 'peace symbol hippie'],
	['✝️', 'cross', 'symbols', 'cross christian religion'],
	['☪️', 'star and crescent', 'symbols', 'star crescent islam muslim'],
	['☯️', 'yin yang', 'symbols', 'yin yang balance tao'],
	['🕉️', 'om', 'symbols', 'om hindu religion symbol'],
	['🛐', 'place of worship', 'symbols', 'worship religion church mosque'],
	['♻️', 'recycling symbol', 'symbols', 'recycle green eco environment'],
	['⚜️', 'fleur-de-lis', 'symbols', 'fleur de lis symbol french'],
	['🔱', 'trident emblem', 'symbols', 'trident emblem symbol'],
	['📛', 'name badge', 'symbols', 'name badge id tag'],
	['🔰', 'beginner symbol', 'symbols', 'beginner japanese leaf symbol'],
	['⭕', 'hollow red circle', 'symbols', 'circle hollow red o mark'],
	['✅', 'check mark button', 'symbols', 'check yes correct done'],
	['❌', 'cross mark', 'symbols', 'cross x wrong incorrect no'],
	['❎', 'cross mark button', 'symbols', 'cross button x no'],
	['➡️', 'right arrow', 'symbols', 'arrow right direction forward'],
	['⬅️', 'left arrow', 'symbols', 'arrow left direction back'],
	['⬆️', 'up arrow', 'symbols', 'arrow up direction top'],
	['⬇️', 'down arrow', 'symbols', 'arrow down direction bottom'],
	['↗️', 'up-right arrow', 'symbols', 'arrow up right direction'],
	['↘️', 'down-right arrow', 'symbols', 'arrow down right direction'],
	['↙️', 'down-left arrow', 'symbols', 'arrow down left direction'],
	['↖️', 'up-left arrow', 'symbols', 'arrow up left direction'],
	['🔄', 'counterclockwise arrows', 'symbols', 'refresh reload rotate sync'],
	['🔃', 'clockwise vertical arrows', 'symbols', 'clockwise arrows reload sync'],
	['🆕', 'new button', 'symbols', 'new fresh button'],
	['🆓', 'free button', 'symbols', 'free gratis button'],
	['🆙', 'up button', 'symbols', 'up upgrade button'],
	['🆒', 'cool button', 'symbols', 'cool awesome button'],
	['🆗', 'OK button', 'symbols', 'ok approved button'],
	['🆖', 'NG button', 'symbols', 'ng no good button'],
	['🆘', 'SOS button', 'symbols', 'sos help emergency button'],
	['🆚', 'VS button', 'symbols', 'vs versus button'],
	['🈁', 'Japanese here button', 'symbols', 'japanese here koko button'],
	['🈶', 'Japanese not free button', 'symbols', 'japanese not free button'],
	['🈯', 'Japanese reserved button', 'symbols', 'japanese reserved button'],
	['🉐', 'Japanese bargain button', 'symbols', 'japanese bargain button'],
	['🈹', 'Japanese discount button', 'symbols', 'japanese discount button'],
	['🈲', 'Japanese prohibited button', 'symbols', 'japanese prohibited button'],
	['🈺', 'Japanese open button', 'symbols', 'japanese open business button'],
	['🈵', 'Japanese full button', 'symbols', 'japanese no vacancy button'],
	['🔴', 'red circle', 'symbols', 'circle red'],
	['🟠', 'orange circle', 'symbols', 'circle orange'],
	['🟡', 'yellow circle', 'symbols', 'circle yellow'],
	['🟢', 'green circle', 'symbols', 'circle green'],
	['🔵', 'blue circle', 'symbols', 'circle blue'],
	['🟣', 'purple circle', 'symbols', 'circle purple'],
	['⚫', 'black circle', 'symbols', 'circle black'],
	['⚪', 'white circle', 'symbols', 'circle white'],
	['🟤', 'brown circle', 'symbols', 'circle brown'],
	['🔶', 'large orange diamond', 'symbols', 'diamond orange large'],
	['🔷', 'large blue diamond', 'symbols', 'diamond blue large'],
	['🔸', 'small orange diamond', 'symbols', 'diamond orange small'],
	['🔹', 'small blue diamond', 'symbols', 'diamond blue small'],
	['🔺', 'red triangle pointed up', 'symbols', 'triangle red up'],
	['🔻', 'red triangle pointed down', 'symbols', 'triangle red down'],
	['💠', 'diamond with a dot', 'symbols', 'diamond dot jewel'],
	['♠️', 'spade suit', 'symbols', 'spade card suit'],
	['♥️', 'heart suit', 'symbols', 'heart card suit love'],
	['♦️', 'diamond suit', 'symbols', 'diamond card suit'],
	['♣️', 'club suit', 'symbols', 'club card suit'],
	['♟️', 'chess pawn', 'symbols', 'chess pawn game piece'],
	['🃏', 'joker', 'symbols', 'joker wild card game'],
	['🀄', 'mahjong red dragon', 'symbols', 'mahjong dragon tile game'],
	['🎴', 'flower playing cards', 'symbols', 'flower cards japanese game'],
	['🔞', 'no one under 18', 'symbols', '18 age restriction adult'],
	['✳️', 'eight-spoked asterisk', 'symbols', 'asterisk eight spoked'],
	['❇️', 'sparkle', 'symbols', 'sparkle star shiny'],
	['💱', 'currency exchange', 'symbols', 'currency exchange money'],
	['💲', 'heavy dollar sign', 'symbols', 'dollar sign money currency'],
	['©️', 'copyright', 'symbols', 'copyright symbol'],
	['®️', 'registered', 'symbols', 'registered trademark symbol'],
	['™️', 'trade mark', 'symbols', 'trademark tm symbol'],
];

const COUNTRIES = [
	['AF', 'Afghanistan'],
	['AL', 'Albania'],
	['DZ', 'Algeria'],
	['AD', 'Andorra'],
	['AO', 'Angola'],
	['AG', 'Antigua & Barbuda'],
	['AR', 'Argentina'],
	['AM', 'Armenia'],
	['AU', 'Australia'],
	['AT', 'Austria'],
	['AZ', 'Azerbaijan'],
	['BS', 'Bahamas'],
	['BH', 'Bahrain'],
	['BD', 'Bangladesh'],
	['BB', 'Barbados'],
	['BY', 'Belarus'],
	['BE', 'Belgium'],
	['BZ', 'Belize'],
	['BJ', 'Benin'],
	['BT', 'Bhutan'],
	['BO', 'Bolivia'],
	['BA', 'Bosnia & Herzegovina'],
	['BW', 'Botswana'],
	['BR', 'Brazil'],
	['BN', 'Brunei'],
	['BG', 'Bulgaria'],
	['BF', 'Burkina Faso'],
	['BI', 'Burundi'],
	['KH', 'Cambodia'],
	['CM', 'Cameroon'],
	['CA', 'Canada'],
	['CV', 'Cape Verde'],
	['CF', 'Central African Republic'],
	['TD', 'Chad'],
	['CL', 'Chile'],
	['CN', 'China'],
	['CO', 'Colombia'],
	['KM', 'Comoros'],
	['CG', 'Congo'],
	['CD', 'Congo DR'],
	['CR', 'Costa Rica'],
	['CI', "Côte d'Ivoire"],
	['HR', 'Croatia'],
	['CU', 'Cuba'],
	['CY', 'Cyprus'],
	['CZ', 'Czechia'],
	['DK', 'Denmark'],
	['DJ', 'Djibouti'],
	['DM', 'Dominica'],
	['DO', 'Dominican Republic'],
	['EC', 'Ecuador'],
	['EG', 'Egypt'],
	['SV', 'El Salvador'],
	['GQ', 'Equatorial Guinea'],
	['ER', 'Eritrea'],
	['EE', 'Estonia'],
	['SZ', 'Eswatini'],
	['ET', 'Ethiopia'],
	['FJ', 'Fiji'],
	['FI', 'Finland'],
	['FR', 'France'],
	['GA', 'Gabon'],
	['GM', 'Gambia'],
	['GE', 'Georgia'],
	['DE', 'Germany'],
	['GH', 'Ghana'],
	['GR', 'Greece'],
	['GD', 'Grenada'],
	['GT', 'Guatemala'],
	['GN', 'Guinea'],
	['GW', 'Guinea-Bissau'],
	['GY', 'Guyana'],
	['HT', 'Haiti'],
	['HN', 'Honduras'],
	['HU', 'Hungary'],
	['IS', 'Iceland'],
	['IN', 'India'],
	['ID', 'Indonesia'],
	['IR', 'Iran'],
	['IQ', 'Iraq'],
	['IE', 'Ireland'],
	['IL', 'Israel'],
	['IT', 'Italy'],
	['JM', 'Jamaica'],
	['JP', 'Japan'],
	['JO', 'Jordan'],
	['KZ', 'Kazakhstan'],
	['KE', 'Kenya'],
	['KI', 'Kiribati'],
	['KP', 'North Korea'],
	['KR', 'South Korea'],
	['KW', 'Kuwait'],
	['KG', 'Kyrgyzstan'],
	['LA', 'Laos'],
	['LV', 'Latvia'],
	['LB', 'Lebanon'],
	['LS', 'Lesotho'],
	['LR', 'Liberia'],
	['LY', 'Libya'],
	['LI', 'Liechtenstein'],
	['LT', 'Lithuania'],
	['LU', 'Luxembourg'],
	['MG', 'Madagascar'],
	['MW', 'Malawi'],
	['MY', 'Malaysia'],
	['MV', 'Maldives'],
	['ML', 'Mali'],
	['MT', 'Malta'],
	['MH', 'Marshall Islands'],
	['MR', 'Mauritania'],
	['MU', 'Mauritius'],
	['MX', 'Mexico'],
	['FM', 'Micronesia'],
	['MD', 'Moldova'],
	['MC', 'Monaco'],
	['MN', 'Mongolia'],
	['ME', 'Montenegro'],
	['MA', 'Morocco'],
	['MZ', 'Mozambique'],
	['MM', 'Myanmar'],
	['NA', 'Namibia'],
	['NR', 'Nauru'],
	['NP', 'Nepal'],
	['NL', 'Netherlands'],
	['NZ', 'New Zealand'],
	['NI', 'Nicaragua'],
	['NE', 'Niger'],
	['NG', 'Nigeria'],
	['MK', 'North Macedonia'],
	['NO', 'Norway'],
	['OM', 'Oman'],
	['PK', 'Pakistan'],
	['PW', 'Palau'],
	['PS', 'Palestine'],
	['PA', 'Panama'],
	['PG', 'Papua New Guinea'],
	['PY', 'Paraguay'],
	['PE', 'Peru'],
	['PH', 'Philippines'],
	['PL', 'Poland'],
	['PT', 'Portugal'],
	['QA', 'Qatar'],
	['RO', 'Romania'],
	['RU', 'Russia'],
	['RW', 'Rwanda'],
	['KN', 'St. Kitts & Nevis'],
	['LC', 'St. Lucia'],
	['VC', 'St. Vincent & Grenadines'],
	['WS', 'Samoa'],
	['SM', 'San Marino'],
	['ST', 'São Tomé & Príncipe'],
	['SA', 'Saudi Arabia'],
	['SN', 'Senegal'],
	['RS', 'Serbia'],
	['SC', 'Seychelles'],
	['SL', 'Sierra Leone'],
	['SG', 'Singapore'],
	['SK', 'Slovakia'],
	['SI', 'Slovenia'],
	['SB', 'Solomon Islands'],
	['SO', 'Somalia'],
	['ZA', 'South Africa'],
	['SS', 'South Sudan'],
	['ES', 'Spain'],
	['LK', 'Sri Lanka'],
	['SD', 'Sudan'],
	['SR', 'Suriname'],
	['SE', 'Sweden'],
	['CH', 'Switzerland'],
	['SY', 'Syria'],
	['TJ', 'Tajikistan'],
	['TZ', 'Tanzania'],
	['TH', 'Thailand'],
	['TL', 'Timor-Leste'],
	['TG', 'Togo'],
	['TO', 'Tonga'],
	['TT', 'Trinidad & Tobago'],
	['TN', 'Tunisia'],
	['TR', 'Turkey'],
	['TM', 'Turkmenistan'],
	['TV', 'Tuvalu'],
	['UG', 'Uganda'],
	['UA', 'Ukraine'],
	['AE', 'United Arab Emirates'],
	['GB', 'United Kingdom'],
	['US', 'United States'],
	['UY', 'Uruguay'],
	['UZ', 'Uzbekistan'],
	['VU', 'Vanuatu'],
	['VA', 'Vatican City'],
	['VE', 'Venezuela'],
	['VN', 'Vietnam'],
	['YE', 'Yemen'],
	['ZM', 'Zambia'],
	['ZW', 'Zimbabwe'],
];

function getFlagEmoji(code) {
	return String.fromCodePoint(...code.split('').map(c => 0x1F1E6 + c.charCodeAt(0) - 65));
}

let _allEmojis = null;

export function getAllEmojis() {
	if (_allEmojis) return _allEmojis;

	const result = EMOJIS.map(e => ({
		emoji: e[0],
		name: e[1],
		category: e[2],
		keywords: e[3].split(' '),
		skinTone: e[4] === true,
		countryCode: null,
	}));

	for (const [code, name] of COUNTRIES) {
		result.push({
			emoji: getFlagEmoji(code),
			name: `flag: ${name}`,
			category: 'flags',
			keywords: [name.toLowerCase(), 'flag', 'country', code.toLowerCase()],
			skinTone: false,
			countryCode: code,
		});
	}

	_allEmojis = result;
	return _allEmojis;
}

export function applySkinTone(emoji, modifier) {
	if (!modifier) return emoji;
	const chars = [...emoji];
	for (let i = 0; i < chars.length; i++) {
		const code = chars[i].codePointAt(0);
		if (code >= 0x1F3FB && code <= 0x1F3FF) {
			chars[i] = modifier;
			return chars.join('');
		}
	}
	return emoji + modifier;
}

function stripVS(s) {
	return s.replace(/\uFE0F/g, '');
}

export function isZwij(emoji) {
	return emoji.indexOf('\u200D') !== -1;
}

export function getEmojiCodepoint(emoji) {
	const cps = [...stripVS(emoji)].map(c => c.codePointAt(0).toString(16).toLowerCase());
	return cps[0];
}

export function searchEmojis(query) {
	if (!query.trim()) return getAllEmojis();
	const q = query.toLowerCase().trim();
	return getAllEmojis().filter(e =>
		e.name.toLowerCase().includes(q) ||
		e.keywords.some(k => k.includes(q)) ||
		(e.countryCode && e.countryCode.toLowerCase() === q)
	);
}

export function getEmojisByCategory(categoryId) {
	if (!categoryId || categoryId === 'all') return getAllEmojis();
	return getAllEmojis().filter(e => e.category === categoryId);
}
